"use client";

import { motion } from "framer-motion";
import { ArrowRight, Check, CheckCircle2, PhoneCall, Route, Target } from "lucide-react";
import { FormEvent, useState } from "react";
import { FadeIn } from "./shared";

const steps = [[Target, "Деңгейіңді анықтаймыз", "Қысқа тегін диагностика"], [Route, "Жеке жоспар құрамыз", "Мақсат пен уақытыңа сай"], [CheckCircle2, "Нәтижеге бірге жетеміз", "Ментор әр қадамда қасыңда"]];

export default function ContactForm() {
  const [sent, setSent] = useState(false);
  function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setSent(true); }
  return <section id="contact" className="relative overflow-hidden bg-slate-900 py-24 text-white sm:py-28"><div className="absolute -left-40 -top-40 size-[32rem] rounded-full bg-blue-600/20 blur-3xl" /><div className="absolute -bottom-48 right-0 size-[30rem] rounded-full bg-cyan-400/10 blur-3xl" /><div className="site-container relative grid items-center gap-14 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><FadeIn><span className="inline-flex rounded-full border border-blue-400/30 bg-blue-400/10 px-4 py-2 text-[10px] font-black tracking-[.14em] text-blue-300">АЛҒАШҚЫ ҚАДАМ</span><h2 className="mt-6 text-4xl font-extrabold tracking-[-.045em] sm:text-5xl">Олимпиадаға дайындықты <span className="text-blue-400">бүгін баста</span></h2><p className="mt-6 max-w-xl text-base leading-7 text-slate-400">Өтінім қалдыр — оқу кеңесшісі хабарласып, тегін диагностикаға жазады.</p><div className="mt-10 space-y-5">{steps.map(([Icon, title, text], i) => <div key={String(title)} className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl border border-blue-400/20 bg-blue-400/10 text-blue-300"><Icon size={19} /></span><div><p className="text-sm font-bold text-white">0{i + 1}. {title}</p><small className="mt-1 block text-slate-500">{text}</small></div></div>)}</div></FadeIn>
    <motion.form onSubmit={submit} initial={{ opacity: 0, y: 30 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="relative min-h-[510px] rounded-2xl border border-slate-200/80 bg-white p-7 text-slate-900 shadow-2xl sm:p-9">{sent ? <div className="flex min-h-[430px] flex-col items-center justify-center text-center"><span className="grid size-16 place-items-center rounded-full bg-emerald-50 text-emerald-600"><Check size={28} /></span><h3 className="mt-6 text-2xl font-extrabold">Өтінім қабылданды!</h3><p className="mt-3 max-w-xs text-sm leading-6 text-slate-500">Кеңесшіміз жақын арада сізбен байланысады.</p><button type="button" onClick={() => setSent(false)} className="primary-button mt-7">Тағы өтінім беру</button></div> : <><span className="absolute right-7 top-7 rounded-full bg-blue-50 px-3 py-1.5 text-[9px] font-black text-blue-600">ТЕГІН</span><PhoneCall size={22} className="text-blue-600" /><h3 className="mt-4 text-2xl font-extrabold">Диагностикаға жазылу</h3><p className="mt-2 text-sm text-slate-500">Байланыс деректеріңізді қалдырыңыз</p><div className="mt-7 space-y-4"><label className="form-label">Аты-жөніңіз<input required name="name" placeholder="Мысалы, Айдана" className="form-input" /></label><label className="form-label">Телефон нөмірі<div className="flex rounded-xl border border-slate-200 bg-slate-50 focus-within:border-blue-500 focus-within:ring-4 focus-within:ring-blue-50"><span className="self-center pl-4 text-sm text-slate-500">+7</span><input required inputMode="tel" name="phone" placeholder="700 000 00 00" className="form-input !border-0 !bg-transparent !ring-0" /></div></label><label className="form-label">Сыныбыңыз<select required defaultValue="" className="form-input"><option value="" disabled>Сыныпты таңдаңыз</option><option>8-сынып</option><option>9-сынып</option><option>10-сынып</option><option>11-сынып</option></select></label></div><button type="submit" className="primary-button mt-6 w-full">Тегін диагностикаға жазылу <ArrowRight size={18} /></button><p className="mt-4 text-center text-[9px] leading-4 text-slate-400">Батырманы басу арқылы дербес деректерді өңдеуге келісесіз</p></>}</motion.form></div></section>;
}
