"use client";

import { motion } from "framer-motion";
import { ArrowUp, Camera, CirclePlay, Send } from "lucide-react";
import { Logo } from "./shared";

export default function Footer() {
  return <motion.footer initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} viewport={{ once: true }} className="bg-slate-950 pb-7 pt-16 text-white"><div className="site-container grid gap-10 border-b border-slate-800 pb-12 md:grid-cols-2 lg:grid-cols-[1.5fr_.7fr_.8fr_1fr]"><div><Logo light /><p className="mt-6 max-w-xs text-sm leading-6 text-slate-500">Пән олимпиадаларына жүйелі дайындық беретін Қазақстандағы заманауи онлайн мектеп.</p><div className="mt-6 flex gap-2">{[Camera, Send, CirclePlay].map((Icon, i) => <a key={i} href="#" aria-label="Әлеуметтік желі" className="grid size-9 place-items-center rounded-xl border border-slate-800 text-slate-400 transition hover:border-blue-500 hover:text-blue-400"><Icon size={16} /></a>)}</div></div><div><h3 className="text-xs font-black uppercase tracking-wider text-white">Навигация</h3>{[["Платформа", "#platform"], ["Артықшылықтар", "#features"], ["Нәтижелер", "#results"], ["Тарифтер", "#pricing"]].map(([x,h]) => <a key={x} href={h} className="mt-4 block text-xs text-slate-500 hover:text-blue-400">{x}</a>)}</div><div><h3 className="text-xs font-black uppercase tracking-wider text-white">Байланыс</h3><a href="#contact" className="mt-4 block text-xs text-slate-500 hover:text-blue-400">Кеңес алу</a><a href="#faq" className="mt-4 block text-xs text-slate-500 hover:text-blue-400">FAQ</a><p className="mt-4 text-xs text-slate-500">Қазақстан · Онлайн</p></div><div className="rounded-2xl border border-blue-400/20 bg-blue-400/10 p-5"><p className="text-sm font-bold">Бірінші қадамға дайынсың ба?</p><a href="#contact" className="mt-5 flex items-center justify-center rounded-xl bg-blue-600 px-4 py-3 text-xs font-black hover:bg-blue-500">Тегін бастау →</a></div></div><div className="site-container flex flex-col gap-4 pt-7 text-[10px] text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>© 2026 ALTYN School. Барлық құқық қорғалған.</span><a href="#top" className="inline-flex items-center gap-2 text-slate-400 hover:text-blue-400">Жоғарыға <ArrowUp size={13} /></a></div></motion.footer>;
}
