"use client";

import { motion } from "framer-motion";
import { BarChart3, BookOpenCheck, ClipboardCheck, Crown, PlayCircle, Smartphone } from "lucide-react";
import { FadeIn, SectionHeading } from "./shared";

const items = [[ClipboardCheck, "Үй тапсырмалары / ПҮ", "Әр тақырыпқа деңгейлік практика"], [BookOpenCheck, "Академиялық конспектілер", "Қысқа әрі түсінікті материал"], [Crown, "Рейтинг / Leaderboard", "Достық жарыс және мотивация"], [BarChart3, "1-on-1 Soft-Check", "Ментордан жеке кері байланыс"]];

export default function LMSPreview() {
  return <section id="platform" className="section-space bg-white"><div className="site-container"><SectionHeading eyebrow="ALTYN LMS" title="Бәрі бір" accent="экожүйеде" description="Сабақ, тапсырма, рейтинг, жеке прогресс және ментор қолдауы — бір ыңғайлы платформада." />
    <div className="grid items-center gap-14 lg:grid-cols-[.82fr_1.18fr]">
      <div className="grid gap-4 sm:grid-cols-2">{items.map(([Icon, title, text], i) => <FadeIn key={String(title)} delay={i * .07}><motion.article whileHover={{ y: -6 }} className="premium-card h-full p-6"><span className="icon-box"><Icon size={21} /></span><h3 className="mt-5 text-base font-extrabold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-blue-600 to-cyan-400" style={{ width: `${64 + i * 8}%` }} /></div></motion.article></FadeIn>)}</div>
      <FadeIn className="relative"><div className="lms-shell"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><div><p className="text-[9px] font-black tracking-[.14em] text-blue-600">ALTYN PLATFORM</p><b className="text-sm text-slate-900">Сәлем, Айдана 👋</b></div><span className="grid size-9 place-items-center rounded-xl bg-blue-50 text-blue-600"><Smartphone size={17} /></span></div><div className="grid gap-4 p-5 sm:grid-cols-[1.2fr_.8fr]"><div><div className="rounded-2xl bg-gradient-to-br from-blue-600 to-blue-700 p-5 text-white"><small className="text-blue-100">Жалпы прогресс</small><div className="mt-3 flex items-end justify-between"><strong className="text-4xl">78%</strong><span className="rounded-full bg-white/15 px-3 py-1 text-[10px]">+12% осы аптада</span></div><div className="mt-4 h-2 rounded-full bg-white/20"><div className="h-full w-[78%] rounded-full bg-white" /></div></div>{["Органикалық химия", "Термодинамика", "Ерітінділер"].map((x, i) => <div key={x} className="mt-3 flex items-center gap-3 rounded-xl border border-slate-100 bg-white p-3 shadow-sm"><span className="grid size-9 place-items-center rounded-lg bg-blue-50 text-xs font-black text-blue-600">0{i + 1}</span><div className="flex-1"><b className="block text-xs text-slate-800">{x}</b><small className="text-[9px] text-slate-400">{6 + i * 2} сабақ · {4 + i} тест</small></div><PlayCircle size={18} className="text-blue-500" /></div>)}</div><div className="rounded-2xl border border-slate-100 bg-slate-50 p-4"><p className="text-[9px] font-black tracking-[.12em] text-slate-400">БҮГІНГІ ЖОСПАР</p><strong className="mt-1 block text-lg text-slate-900">3 тапсырма</strong><div className="my-4 h-2 rounded-full bg-slate-200"><div className="h-full w-2/3 rounded-full bg-blue-600" /></div>{["Видео сабақ", "Тақырыптық тест", "Ментормен талдау"].map((x, i) => <p key={x} className="my-3 flex items-center gap-2 text-[10px] font-semibold text-slate-600"><span className={`grid size-5 place-items-center rounded-full ${i < 2 ? "bg-emerald-100 text-emerald-600" : "bg-white text-slate-400"}`}>{i < 2 ? "✓" : "○"}</span>{x}</p>)}</div></div></div></FadeIn>
    </div></div></section>;
}
