"use client";

import { motion } from "framer-motion";
import { Check, Flame, Sparkles } from "lucide-react";
import { FadeIn, SectionHeading } from "./shared";

const plans = [
  { name: "Group", label: "SYSTEM INTENSIVE", price: "30 000", desc: "8 апталық жүйе және топтық ментор қолдауы", features: ["30+ академиялық дәріс", "30 практикалық блок", "8 апталық срез және қате талдауы", "Апталық live-практика", "Guest Lectures & Tea Time"], featured: false },
  { name: "Mentor", label: "PERSONAL FOCUS", price: "40 000", desc: "Интенсив жүйесі және жеке терең кері байланыс", features: ["Group форматының барлық мүмкіндігі", "Жеке дайындық траекториясы", "Тұрақты 1-on-1 талдау", "Қателермен жеке жұмыс", "Олимпиада кезеңіне бейімдеу", "Басымдықпен кері байланыс"], featured: true },
];

export default function Pricing() {
  return <section id="pricing" className="section-space bg-white"><div className="site-container"><SectionHeading eyebrow="ОҚУ ФОРМАТЫ" title="Бір жүйе —" accent="екі қолдау деңгейі" description="Екі форматта да 8 апталық ALTYN System толық беріледі. Айырмашылығы — жеке менторлық қолдаудың тереңдігінде." /><div className="mx-auto grid max-w-5xl gap-7 md:grid-cols-2">{plans.map((plan, i) => <FadeIn key={plan.name} delay={i * .1}><motion.article whileHover={{ y: -8 }} className={`relative h-full rounded-[2rem] bg-white p-8 transition-all duration-300 ${plan.featured ? "border-2 border-[#2eb9eb] shadow-[0_25px_70px_rgba(46,185,235,.18)]" : "border border-sky-200 shadow-[0_4px_80px_rgba(0,0,0,.05)] hover:shadow-xl"}`}>{plan.featured && <div className="absolute -top-4 left-1/2 flex -translate-x-1/2 items-center gap-1.5 rounded-full bg-[#2eb9eb] px-4 py-2 text-[10px] font-black tracking-[.12em] text-white shadow-lg"><Flame size={13} /> ЖЕКЕ ФОКУС</div>}<div className="flex items-center justify-between"><span className={`grid size-12 place-items-center rounded-2xl ${plan.featured ? "bg-[#2eb9eb] text-white" : "bg-blue-50 text-blue-600"}`}><Sparkles size={21} /></span><span className="text-[9px] font-black tracking-[.14em] text-blue-600">{plan.label}</span></div><h3 className="mt-6 text-3xl font-extrabold text-slate-900">{plan.name}</h3><p className="mt-2 text-sm text-slate-500">{plan.desc}</p><div className="mt-7 border-b border-slate-100 pb-7"><strong className="text-4xl font-extrabold tracking-tight text-slate-900">{plan.price}</strong><span className="ml-2 text-sm font-semibold text-slate-400">KZT / ай</span></div><ul className="my-7 space-y-4">{plan.features.map(x => <li key={x} className="flex items-start gap-3 text-sm text-slate-600"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-600"><Check size={12} strokeWidth={3} /></span>{x}</li>)}</ul><a href="#contact" className={plan.featured ? "primary-button w-full" : "secondary-button w-full"}>{plan.name} туралы білу <span>→</span></a></motion.article></FadeIn>)}</div><p className="mt-8 text-center text-xs text-slate-500">Қай формат лайық екенін білмесең, өтінім қалдыр — команда саған қолдау деңгейін таңдауға көмектеседі.</p></div></section>;
}
