"use client";

import { motion } from "framer-motion";
import { Check, Flame, Sparkles } from "lucide-react";
import { FadeIn, SectionHeading } from "./shared";

const plans = [
  { name: "Junior", label: "FOUNDATION FOCUS", price: "30 000", desc: "Жүйелі базалық дайындық", features: ["Апталық олимпиадалық сынақ", "Видео сабақтар мен конспектілер", "Тақырыптық тесттер", "Топтық ментор қолдауы", "Ай сайынғы прогресс есебі"], featured: false },
  { name: "Pro Mentor", label: "OLYMPIAD FOCUS", price: "40 000", desc: "Максималды жеке нәтиже", features: ["Junior тарифінің барлық мүмкіндігі", "Жеке оқу траекториясы", "Апталық 1-on-1 менторлық", "Қателермен жеке жұмыс", "Олимпиадаға дейін толық сүйемелдеу", "Басымдықпен кері байланыс"], featured: true },
];

export default function Pricing() {
  return <section id="pricing" className="section-space bg-gradient-to-b from-blue-50/60 to-slate-50"><div className="site-container"><SectionHeading eyebrow="ТАРИФТЕР" title="Мақсатыңа сай" accent="форматты таңда" description="Сапалы контент екі тарифте де бар. Айырмашылығы — ментордың жеке қолдау деңгейінде." /><div className="mx-auto grid max-w-4xl gap-7 md:grid-cols-2">{plans.map((plan, i) => <FadeIn key={plan.name} delay={i * .1}><motion.article whileHover={{ y: -8 }} className={`relative h-full rounded-2xl bg-white p-8 transition-all duration-300 ${plan.featured ? "border-2 border-blue-500 shadow-[0_25px_70px_rgba(37,99,235,.20)]" : "border border-slate-200/80 shadow-sm hover:shadow-xl"}`}>{plan.featured && <div className="absolute -top-4 left-1/2 flex -translate-x-1/2 items-center gap-1.5 rounded-full bg-blue-600 px-4 py-2 text-[10px] font-black tracking-[.12em] text-white shadow-lg"><Flame size={13} /> ТОП ТАҢДАУ</div>}<div className="flex items-center justify-between"><span className={`grid size-12 place-items-center rounded-2xl ${plan.featured ? "bg-blue-600 text-white" : "bg-blue-50 text-blue-600"}`}><Sparkles size={21} /></span><span className="text-[9px] font-black tracking-[.14em] text-blue-600">{plan.label}</span></div><h3 className="mt-6 text-3xl font-extrabold text-slate-900">{plan.name}</h3><p className="mt-2 text-sm text-slate-500">{plan.desc}</p><div className="mt-7 border-b border-slate-100 pb-7"><strong className="text-4xl font-extrabold tracking-tight text-slate-900">{plan.price}</strong><span className="ml-2 text-sm font-semibold text-slate-400">KZT / ай</span></div><ul className="my-7 space-y-4">{plan.features.map(x => <li key={x} className="flex items-start gap-3 text-sm text-slate-600"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-blue-50 text-blue-600"><Check size={12} strokeWidth={3} /></span>{x}</li>)}</ul><a href="#contact" className={plan.featured ? "primary-button w-full" : "secondary-button w-full"}>{plan.name} таңдау <span>→</span></a></motion.article></FadeIn>)}</div><p className="mt-8 text-center text-xs text-slate-500">Қай тариф лайық екенін білмесең, тегін диагностикадан өт — біз көмектесеміз.</p></div></section>;
}
